services:
  app:
    build:
      context: .
    ports:
      - "3500:3500"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      ENV: local
    command: sh -c "go mod tidy && go run cmd/masmaint/main.go"